import { Exo_2, Gidole} from "next/font/google";
import "./globals.css";
import NavTop from "./components/navTop";

const exo2 = Exo_2({
  variable: "--font-exo2",
  subsets: ["latin"],
});

const gidole = Gidole({
  variable: "--font-gidole",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${exo2.variable} ${gidole.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavTop />
        <main>{children}</main></body>
    </html>
  );
}
